version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default:ro
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=jobapplier
      - DB_USERNAME=sa
      - DB_PASSWORD=your_strong_password_here
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DISPLAY=host.docker.internal:0.0

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jobapplier
      MYSQL_USER: sa
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ROOT_HOST: "%"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
